#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
JS_FILES=()
JS_FILES_COUNTER=0
CSS_FILES=()
CSS_FILES_COUNTER=0
for FILE in $STAGED_FILES
do
  if [[ "$FILE" =~ .js$ ]]; then
    JS_FILES[JS_FILES_COUNTER]="$FILE"
    (( JS_FILES_COUNTER++ ))
  elif [[ "$FILE" =~ .css$ ]]; then
    CSS_FILES[CSS_FILES_COUNTER]="$FILE"
    (( CSS_FILES_COUNTER++ ))
  fi
done

# echo ${JS_FILES[*]}
# echo ${CSS_FILES[*]}
# exit 0

PASS=true

if [[ ${#JS_FILES[*]} = 0 ]]; then
  echo "no js file changed"
else
  # Check for eslint
  ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
  if [[ ! -x "$ESLINT" ]]; then
    echo "\t\033[41mPlease install ESlint\033[0m (npm i --save --save-exact --dev eslint)"
    exit 1
  fi
  for FILE in ${JS_FILES[*]}
  do
    "$ESLINT" "$FILE" --quiet --fix
    if [[ "$?" == 0 ]]; then
      echo "\t\033[32mESLint Passed: $FILE\033[0m"
    else
      echo "\t\033[41mESLint Failed: $FILE\033[0m"
      PASS=false
    fi
  done
  echo "\nJavascript validation completed!\n"
fi

if [[ ${#CSS_FILES[*]} = 0 ]]; then
  echo "no css file changed"
else
  # Check for stylelint
  STYLELINT="$(git rev-parse --show-toplevel)/node_modules/.bin/stylelint"
  if [[ ! -x "$STYLELINT" ]]; then
    echo "\t\033[41mPlease install stylelint\033[0m (npm i --save --save-exact --dev stylelint)"
    exit 1
  fi
  for FILE in ${CSS_FILES[*]}
  do
    "$STYLELINT" "$FILE" --quiet --fix
    if [[ "$?" == 0 ]]; then
      echo "\t\033[32mStylelint Passed: $FILE\033[0m"
    else
      echo "\t\033[41mStylelint Failed: $FILE\033[0m"
      PASS=false
    fi
  done
  echo "\nCss validation completed!\n"
fi

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass linters but do not. Please fix and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
exit $?